In [24]:
import pandas as pd

In [25]:
all_variants_file_name = "WHO_resistance_variants_all"
high_confidence_variants_file_name = "WHO_resistance_variants_high_confidence"
year = "2023"

In [36]:
all_data = pd.read_excel("WHO-UCN-TB-2023.6-eng.xlsx", sheet_name="Catalogue_master_file", skiprows=2, engine='openpyxl')
all_data

/work/pi_annagreen_umass_edu/saishradha/miniconda3/envs/catalog_map/lib/python3.6/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

,drug,gene,mutation,variant,tier,effect,genomic position,algorithm_pass,Present_SOLO_SR,Present_SOLO_R,...,Additional grading criteria applied,FINAL CONFIDENCE GRADING,Comment,CHANGES vs ver1,"Relaxed thresholds simulation (BDQ_Rv0678, CFZ_Rv0678, INH_katG, DLM_ddn/fbiA/fbiB/fbiC/fgd1/Rv2983)",Silent mutation,Listed in abridged tables,Additional grading,Footnote,CHANGES vs ver1.1
0,Amikacin,bacA,c.102G>A,bacA_c.102G>A,2,synonymous_variant,"(see ""Genomic_coordinates"" sheet)",NaN,NaN,NaN,...,Silent mutation,4) Not assoc w R - Interim,NaN,Now listed,NaN,Silent mutation,no,NaN,NaN,0
1,Amikacin,bacA,c.1044G>A,bacA_c.1044G>A,2,synonymous_variant,"(see ""Genomic_coordinates"" sheet)",NaN,NaN,NaN,...,NaN,5) Not assoc w R,NaN,Now listed,NaN,Silent mutation,no,NaN,NaN,0
2,Amikacin,bacA,c.105C>G,bacA_c.105C>G,2,synonymous_variant,"(see ""Genomic_coordinates"" sheet)",NaN,NaN,NaN,...,Silent mutation,4) Not assoc w R - Interim,NaN,Now listed,NaN,Silent mutation,no,NaN,NaN,0
3,Amikacin,bacA,c.1065T>G,bacA_c.1065T>G,2,synonymous_variant,"(see ""Genomic_coordinates"" sheet)",NaN,NaN,NaN,...,Silent mutation,4) Not assoc w R - Interim,NaN,Now listed,NaN,Silent mutation,no,NaN,NaN,0
4,Amikacin,bacA,c.1080G>A,bacA_c.1080G>A,2,synonymous_variant,"(see ""Genomic_coordinates"" sheet)",NaN,NaN,NaN,...,Silent mutation,4) Not assoc w R - Interim,NaN,Now listed,NaN,Silent mutation,no,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48147,Streptomycin,whiB7,p.Val38Leu,whiB7_p.Val38Leu,1,missense_variant,"(see ""Genomic_coordinates"" sheet)",1.0,1.0,0.0,...,NaN,3) Uncertain significance,NaN,No change,NaN,NaN,no,NaN,NaN,1
48148,Streptomycin,whiB7,p.Val65fs,whiB7_p.Val65fs,1,frameshift,"(see ""Genomic_coordinates"" sheet)",1.0,1.0,0.0,...,NaN,3) Uncertain significance,NaN,No change,NaN,NaN,no,NaN,NaN,1
48149,Streptomycin,whiB7,p.Val65Phe,whiB7_p.Val65Phe,1,missense_variant,"(see ""Genomic_coordinates"" sheet)",0.0,0.0,0.0,...,NaN,3) Uncertain significance,NaN,New Uncertain,NaN,NaN,no,NaN,NaN,0
48150,Streptomycin,whiB7,p.Val6Phe,whiB7_p.Val6Phe,1,missense_variant,"(see ""Genomic_coordinates"" sheet)",1.0,1.0,0.0,...,NaN,3) Uncertain significance,NaN,New Uncertain,NaN,NaN,no,NaN,NaN,0
48151,Streptomycin,whiB7,p.Val91Gly,whiB7_p.Val91Gly,1,missense_variant,"(see ""Genomic_coordinates"" sheet)",0.0,0.0,0.0,...,NaN,3) Uncertain significance,NaN,New Uncertain,NaN,NaN,no,NaN,NaN,0

In [8]:
katG_rows = all_data[all_data["gene"] == "katG"]
katG_rows

,drug,gene,mutation,variant,tier,effect,genomic position,algorithm_pass,Present_SOLO_SR,Present_SOLO_R,...,Additional grading criteria applied,FINAL CONFIDENCE GRADING,Comment,CHANGES vs ver1,"Relaxed thresholds simulation (BDQ_Rv0678, CFZ_Rv0678, INH_katG, DLM_ddn/fbiA/fbiB/fbiC/fgd1/Rv2983)",Silent mutation,Listed in abridged tables,Additional grading,Footnote,CHANGES vs ver1.1
21196,Isoniazid,katG,c.1008G>T,katG_c.1008G>T,1,synonymous_variant,"(see ""Genomic_coordinates"" sheet)",NaN,NaN,NaN,...,Silent mutation,4) Not assoc w R - Interim,NaN,Now listed,NaN,Silent mutation,no,NaN,NaN,0
21197,Isoniazid,katG,c.-100G>A,katG_c.-100G>A,1,upstream_gene_variant,2156211,1.0,2.0,0.0,...,NaN,3) Uncertain significance,NaN,No change,NaN,NaN,no,NaN,NaN,1
21198,Isoniazid,katG,c.1014C>G,katG_c.1014C>G,1,synonymous_variant,"(see ""Genomic_coordinates"" sheet)",1.0,NaN,NaN,...,Silent mutation,4) Not assoc w R - Interim,NaN,Now listed,NaN,Silent mutation,no,NaN,NaN,0
21199,Isoniazid,katG,c.1014C>T,katG_c.1014C>T,1,synonymous_variant,"(see ""Genomic_coordinates"" sheet)",1.0,NaN,NaN,...,Silent mutation,4) Not assoc w R - Interim,NaN,Now listed,NaN,Silent mutation,no,NaN,NaN,0
21200,Isoniazid,katG,c.1029G>A,katG_c.1029G>A,1,synonymous_variant,"(see ""Genomic_coordinates"" sheet)",1.0,NaN,NaN,...,Silent mutation,4) Not assoc w R - Interim,NaN,Now listed,NaN,Silent mutation,no,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22718,Isoniazid,katG,p.Val73Ala,katG_p.Val73Ala,1,missense_variant,"(see ""Genomic_coordinates"" sheet)",1.0,2.0,0.0,...,NaN,3) Uncertain significance,NaN,New Uncertain,NaN,NaN,no,NaN,NaN,0
22719,Isoniazid,katG,p.Val73Gly,katG_p.Val73Gly,1,missense_variant,"(see ""Genomic_coordinates"" sheet)",0.0,0.0,0.0,...,NaN,3) Uncertain significance,NaN,No change,NaN,NaN,no,NaN,NaN,1
22720,Isoniazid,katG,p.Val83fs,katG_p.Val83fs,1,frameshift,"(see ""Genomic_coordinates"" sheet)",2.0,1.0,1.0,...,Indel frameshift or premature stop codon (LoF),2) Assoc w R - Interim,High-level resistance,No change,NaN,NaN,no,NaN,G,1
22721,Isoniazid,katG,p.Val83Gly,katG_p.Val83Gly,1,missense_variant,"(see ""Genomic_coordinates"" sheet)",0.0,0.0,0.0,...,NaN,3) Uncertain significance,NaN,New Uncertain,NaN,NaN,no,NaN,NaN,0
22722,Isoniazid,katG,p.Val83Leu,katG_p.Val83Leu,1,missense_variant,"(see ""Genomic_coordinates"" sheet)",0.0,0.0,0.0,...,NaN,3) Uncertain significance,NaN,No change,NaN,NaN,no,NaN,NaN,1

In [9]:
genome_indices = pd.read_excel("WHO-UCN-TB-2023.6-eng.xlsx", sheet_name="Genomic_coordinates", engine='openpyxl')
genome_indices

,variant,chromosome,position,reference_nucleotide,alternative_nucleotide
0,dnaA_p.Asp3Ala,NC_000962.3,8,AT,CC
1,dnaA_p.Asp3Ala,NC_000962.3,8,A,C
2,dnaA_p.Asp3Ala,NC_000962.3,8,AT,CG
3,dnaA_p.Asp3Ala,NC_000962.3,8,AT,CA
4,dnaA_p.Asp4His,NC_000962.3,10,G,C
...,...,...,...,...,...
146374,dnaA_c.-15C>T,NC_000962.3,4411518,C,T
146375,dnaA_c.-14A>C,NC_000962.3,4411519,A,C
146376,dnaA_c.-13G>C,NC_000962.3,4411520,G,C
146377,dnaA_c.-13G>A,NC_000962.3,4411520,G,A
146378,dnaA_c.-11G>A,NC_000962.3,4411522,G,A

In [10]:
katG_index = genome_indices[genome_indices["variant"] == "katG_c.-85C>T"]
katG_index

,variant,chromosome,position,reference_nucleotide,alternative_nucleotide
79452,katG_c.-85C>T,NC_000962.3,2156196,G,A

In [11]:
# Remove rows with multiple positions separated by commas
genome_indices = genome_indices[~genome_indices['position'].astype(str).str.contains(',')]
genome_indices

,variant,chromosome,position,reference_nucleotide,alternative_nucleotide
0,dnaA_p.Asp3Ala,NC_000962.3,8,AT,CC
1,dnaA_p.Asp3Ala,NC_000962.3,8,A,C
2,dnaA_p.Asp3Ala,NC_000962.3,8,AT,CG
3,dnaA_p.Asp3Ala,NC_000962.3,8,AT,CA
4,dnaA_p.Asp4His,NC_000962.3,10,G,C
...,...,...,...,...,...
146374,dnaA_c.-15C>T,NC_000962.3,4411518,C,T
146375,dnaA_c.-14A>C,NC_000962.3,4411519,A,C
146376,dnaA_c.-13G>C,NC_000962.3,4411520,G,C
146377,dnaA_c.-13G>A,NC_000962.3,4411520,G,A
146378,dnaA_c.-11G>A,NC_000962.3,4411522,G,A

In [12]:
m = all_data[['drug','variant', 'mutation', 'FINAL CONFIDENCE GRADING']].merge(
    genome_indices[["variant", "position","reference_nucleotide", "alternative_nucleotide"]], 
    left_on="variant", 
    right_on="variant", how='left'
).dropna(subset=["variant", "position"])

m.columns = ['drug', "variant", "mutation", "confidence", "genome_index", "ref_nt", "alt_nt"]

m = m.query("confidence != 'combo'")

m["gene"] = [x.split("_")[0] for x in m.variant]
m

,drug,variant,mutation,confidence,genome_index,ref_nt,alt_nt,gene
0,Amikacin,bacA_c.102G>A,c.102G>A,4) Not assoc w R - Interim,2064627.0,C,T,bacA
1,Amikacin,bacA_c.1044G>A,c.1044G>A,5) Not assoc w R,2063685.0,C,T,bacA
2,Amikacin,bacA_c.1044G>A,c.1044G>A,5) Not assoc w R,2063685.0,CAA,TAG,bacA
3,Amikacin,bacA_c.105C>G,c.105C>G,4) Not assoc w R - Interim,2064624.0,G,C,bacA
4,Amikacin,bacA_c.1065T>G,c.1065T>G,4) Not assoc w R - Interim,2063658.0,TAATCGA,CAACCGC,bacA
...,...,...,...,...,...,...,...,...
203904,Streptomycin,whiB7_p.Val6Phe,p.Val6Phe,3) Uncertain significance,3568664.0,C,A,whiB7
203905,Streptomycin,whiB7_p.Val91Gly,p.Val91Gly,3) Uncertain significance,3568407.0,AA,TC,whiB7
203906,Streptomycin,whiB7_p.Val91Gly,p.Val91Gly,3) Uncertain significance,3568407.0,AA,CC,whiB7
203907,Streptomycin,whiB7_p.Val91Gly,p.Val91Gly,3) Uncertain significance,3568407.0,AA,GC,whiB7
203908,Streptomycin,whiB7_p.Val91Gly,p.Val91Gly,3) Uncertain significance,3568408.0,A,C,whiB7

In [13]:
# import pandas as pd
# import numpy as np
# import re

# # Sample data
# data = {
#     'variant': ['rrs_a1401g', 'eis_c-14t', 'rrs_g1484t', 'whiB6_A77V', 'gid_Y195H', 'whiB7_192_del_1_gc_g']
# }
# df = pd.DataFrame(data)

# x = df['variant'].str.split('_').str[1].tolist()
# print(x)
# df['number'] = [int(k) for s in x for k in re.findall(r'-?\d+\.?\d*', s)]

# print(df[['variant', 'number']])

In [14]:
m.genome_index = [str(x).replace(',',';') for x in m.genome_index]
m
# full_mapping.query("variant=='rpoB_S450Q'")

,drug,variant,mutation,confidence,genome_index,ref_nt,alt_nt,gene
0,Amikacin,bacA_c.102G>A,c.102G>A,4) Not assoc w R - Interim,2064627.0,C,T,bacA
1,Amikacin,bacA_c.1044G>A,c.1044G>A,5) Not assoc w R,2063685.0,C,T,bacA
2,Amikacin,bacA_c.1044G>A,c.1044G>A,5) Not assoc w R,2063685.0,CAA,TAG,bacA
3,Amikacin,bacA_c.105C>G,c.105C>G,4) Not assoc w R - Interim,2064624.0,G,C,bacA
4,Amikacin,bacA_c.1065T>G,c.1065T>G,4) Not assoc w R - Interim,2063658.0,TAATCGA,CAACCGC,bacA
...,...,...,...,...,...,...,...,...
203904,Streptomycin,whiB7_p.Val6Phe,p.Val6Phe,3) Uncertain significance,3568664.0,C,A,whiB7
203905,Streptomycin,whiB7_p.Val91Gly,p.Val91Gly,3) Uncertain significance,3568407.0,AA,TC,whiB7
203906,Streptomycin,whiB7_p.Val91Gly,p.Val91Gly,3) Uncertain significance,3568407.0,AA,CC,whiB7
203907,Streptomycin,whiB7_p.Val91Gly,p.Val91Gly,3) Uncertain significance,3568407.0,AA,GC,whiB7
203908,Streptomycin,whiB7_p.Val91Gly,p.Val91Gly,3) Uncertain significance,3568408.0,A,C,whiB7

In [15]:
m

,drug,variant,mutation,confidence,genome_index,ref_nt,alt_nt,gene
0,Amikacin,bacA_c.102G>A,c.102G>A,4) Not assoc w R - Interim,2064627.0,C,T,bacA
1,Amikacin,bacA_c.1044G>A,c.1044G>A,5) Not assoc w R,2063685.0,C,T,bacA
2,Amikacin,bacA_c.1044G>A,c.1044G>A,5) Not assoc w R,2063685.0,CAA,TAG,bacA
3,Amikacin,bacA_c.105C>G,c.105C>G,4) Not assoc w R - Interim,2064624.0,G,C,bacA
4,Amikacin,bacA_c.1065T>G,c.1065T>G,4) Not assoc w R - Interim,2063658.0,TAATCGA,CAACCGC,bacA
...,...,...,...,...,...,...,...,...
203904,Streptomycin,whiB7_p.Val6Phe,p.Val6Phe,3) Uncertain significance,3568664.0,C,A,whiB7
203905,Streptomycin,whiB7_p.Val91Gly,p.Val91Gly,3) Uncertain significance,3568407.0,AA,TC,whiB7
203906,Streptomycin,whiB7_p.Val91Gly,p.Val91Gly,3) Uncertain significance,3568407.0,AA,CC,whiB7
203907,Streptomycin,whiB7_p.Val91Gly,p.Val91Gly,3) Uncertain significance,3568407.0,AA,GC,whiB7
203908,Streptomycin,whiB7_p.Val91Gly,p.Val91Gly,3) Uncertain significance,3568408.0,A,C,whiB7

In [16]:
file_name = all_variants_file_name + "_" + year + ".csv"
m[["drug", "genome_index", "confidence", "gene", "variant", "ref_nt", "alt_nt"]].to_csv(file_name, index=False)

In [17]:
m.confidence.unique()

array(['4) Not assoc w R - Interim', '5) Not assoc w R',
       '3) Uncertain significance', '2) Assoc w R - Interim',
       '1) Assoc w R'], dtype=object)

In [18]:
file_name = high_confidence_variants_file_name + "_" + year + ".csv"
m.query("confidence=='1) Assoc w R' or confidence=='2) Assoc w R - Interim'").to_csv(file_name, index=False)

In [20]:
isoniazid_data = m[m["drug"] == "Isoniazid"]
isoniazid_data = isoniazid_data[isoniazid_data["confidence"].isin(["1) Assoc w R'", "2) Assoc w R - Interim"])]
isoniazid_data

,drug,variant,mutation,confidence,genome_index,ref_nt,alt_nt,gene
108181,Isoniazid,inhA_c.-770T>A,c.-770T>A,2) Assoc w R - Interim,1673432.0,T,A,inhA
108182,Isoniazid,inhA_c.-770T>C,c.-770T>C,2) Assoc w R - Interim,1673432.0,T,C,inhA
108183,Isoniazid,inhA_c.-770T>G,c.-770T>G,2) Assoc w R - Interim,1673432.0,T,G,inhA
108189,Isoniazid,inhA_c.-778A>G,c.-778A>G,2) Assoc w R - Interim,1673424.0,AC,GT,inhA
108190,Isoniazid,inhA_c.-778A>G,c.-778A>G,2) Assoc w R - Interim,1673424.0,A,G,inhA
...,...,...,...,...,...,...,...,...
116009,Isoniazid,katG_p.Val83fs,p.Val83fs,2) Assoc w R - Interim,2155860.0,CATCA,C,katG
116010,Isoniazid,katG_p.Val83fs,p.Val83fs,2) Assoc w R - Interim,2155861.0,ATCAC,A,katG
116011,Isoniazid,katG_p.Val83fs,p.Val83fs,2) Assoc w R - Interim,2155864.0,A,AGCGAGATCATGTCGGCCTTGAG,katG
116012,Isoniazid,katG_p.Val83fs,p.Val83fs,2) Assoc w R - Interim,2155864.0,A,AGCGAGATCATGTCGGC,katG
116013,Isoniazid,katG_p.Val83fs,p.Val83fs,2) Assoc w R - Interim,2155864.0,A,AG,katG

In [79]:
m.query("ref_nt=='gcggtgcgcatctcctccagcgcggcgacggtgg'")

,drug,confidence,variant_parsed,gene,variant,genome_index,ref_nt,alt_nt,variant_mapping,first_diff_position,from_nt,to_nt
13149,PZA,1) Assoc w R,NaN,pncA,pncA_533_ins_1_gcggtgcgcatctcctccagcgcggcgacgg...,2288709,gcggtgcgcatctcctccagcgcggcgacggtgg,gcggtgcgcatctcctcccagcgcggcgacggtgg,pncA_533_ins_1_gcggtgcgcatctcctccagcgcggcgacgg...,<NA>,a;g;c;g;c;g;c;g;a;c;g;t;g,c;a;g;c;g;c;g;c;g;a;c;g;t
13433,PZA,2) Assoc w R - Interim,NaN,pncA,pncA_533_ins_2_gcggtgcgcatctcctccagcgcggcgacgg...,2288709,gcggtgcgcatctcctccagcgcggcgacggtgg,gcggtgcgcatctcctccagcgcgcggcgacggtgg,pncA_533_ins_2_gcggtgcgcatctcctccagcgcggcgacgg...,<NA>,g;c;a;c;g;g;t;g,c;g;c;g;a;c;g;t
13434,PZA,2) Assoc w R - Interim,NaN,pncA,pncA_533_ins_2_gcggtgcgcatctcctccagcgcggcgacgg...,2288709,gcggtgcgcatctcctccagcgcggcgacggtgg,gcggtgcgcgcatctcctccagcgcggcgacggtgg,pncA_533_ins_2_gcggtgcgcatctcctccagcgcggcgacgg...,<NA>,a;t;c;c;t;c;a;g;c;g;c;a;c;g;g;t;g,g;c;a;t;c;t;c;c;a;c;g;c;g;a;c;g;t

In [58]:
# find how many rows of full mapping dataframe's genome_index column have multiple values
full_mapping.genome_index.apply(lambda x: len(x.split(";"))).value_counts()

genome_index
1    17365
2      161
3        7
Name: count, dtype: int64

In [59]:
def first_different_position(row):
    if len(row['genome_index'].split(';')) > 1:
        for i, (ref_char, alt_char) in enumerate(zip(row['ref_nt'], row['alt_nt'])):
            if ref_char != alt_char:
                return i + 1  # Adding 1 to make the position 1-indexed
    return None  # Return None for rows with single values in genome_index or no difference found

# Apply the function to each row and store the results in a new column
full_mapping['first_diff_position'] = full_mapping.apply(first_different_position, axis=1).astype('Int64')

In [60]:
filtered_rows = full_mapping[full_mapping['first_diff_position'].notna()]
filtered_rows

,drug,confidence,variant_parsed,gene,variant,genome_index,ref_nt,alt_nt,variant_mapping,first_diff_position
193,AMI,3) Uncertain significance,NaN,aftB,aftB_S159A,4268362;4268360,tca,gcg,aftB_S159A,1
194,AMI,3) Uncertain significance,NaN,aftB,aftB_S238G,4268125;4268123,agt,ggc,aftB_S238G,1
213,AMI,3) Uncertain significance,NaN,aftB,aftB_W63Y,4268649;4268648,tgg,tat,aftB_W63Y,2
253,AMI,3) Uncertain significance,NaN,ccsA,ccsA_I123A,620257;620258,atc,gcc,ccsA_I123A,1
264,AMI,3) Uncertain significance,NaN,ccsA,ccsA_R131K,620281;620282;620283,cgt,aaa,ccsA_R131K,1
...,...,...,...,...,...,...,...,...,...,...
16028,STM,1) Assoc w R,NaN,rpsL,rpsL_K43R,781686;781687,aag,cgg,rpsL_K43R,1
16270,STM,3) Uncertain significance,NaN,gid,gid_E92G,4407928;4407927,gaa,ggc,gid_E92G,2
16426,STM,3) Uncertain significance,NaN,gid,gid_A138L,4407791;4407790,gcg,ttg,gid_A138L,1
17284,STM,3) Uncertain significance,NaN,gid,gid_G69I,4407998;4407997,ggt,att,gid_G69I,1
17463,STM,3) Uncertain significance,NaN,whiB7,whiB7_C20Y,3568621;3568620,tgc,tat,whiB7_C20Y,2

1. Find position of first change in the ref_nt to alt_nt strings. This position is represented by i index in the ref_nt string.
2. Do mod(genome_index[j]-genome_index[0]) index to find the next change. 
3. Get the character at the i+mod(genome_index[j]-genome_index[0]) index of the alt_nt string.

In [61]:
# def extract_changes(row):
#     from_chars = []
#     to_chars = []
    
#     # Check for NaN values before processing
#     if pd.notna(row['ref_nt']) and pd.notna(row['alt_nt']):
#         for ref_char, alt_char in zip(row['ref_nt'], row['alt_nt']):
#             if ref_char != alt_char:
#                 from_chars.append(ref_char)
#                 to_chars.append(alt_char)
    
#     return pd.Series({'from_nt': ';'.join(from_chars), 'to_nt': ';'.join(to_chars)})

# # Apply the function and join the result with the original dataframe
# changes_df = full_mapping.apply(extract_changes, axis=1)
# full_mapping = pd.concat([full_mapping, changes_df], axis=1)

In [62]:
# give me the rows where the first_diff_position is not null
# full_mapping.query("first_diff_position.notna()")

In [70]:
# Create masks for changes and for non-NaN values
change_mask = full_mapping['ref_nt'] != full_mapping['alt_nt']
non_nan_mask = ~full_mapping[['ref_nt', 'alt_nt']].isna().any(axis=1)

# Apply masks to filter the rows that need change
indices_to_change = full_mapping[change_mask & non_nan_mask].index

# Extract characters where there's a difference
full_mapping.loc[indices_to_change, 'from_nt'] = ["".join([ref for ref, alt in zip(row['ref_nt'], row['alt_nt']) if ref != alt]) for _, row in full_mapping.loc[indices_to_change].iterrows()]
full_mapping.loc[indices_to_change, 'to_nt'] = ["".join([alt for ref, alt in zip(row['ref_nt'], row['alt_nt']) if ref != alt]) for _, row in full_mapping.loc[indices_to_change].iterrows()]

# Fill NaN values for rows where there were no changes or had NaN values initially
full_mapping[['from_nt', 'to_nt']] = full_mapping[['from_nt', 'to_nt']].fillna("")

In [71]:
full_mapping.query("first_diff_position.notna()")

,drug,confidence,variant_parsed,gene,variant,genome_index,ref_nt,alt_nt,variant_mapping,first_diff_position,from_nt,to_nt
193,AMI,3) Uncertain significance,NaN,aftB,aftB_S159A,4268362;4268360,tca,gcg,aftB_S159A,1,t;a,g;g
194,AMI,3) Uncertain significance,NaN,aftB,aftB_S238G,4268125;4268123,agt,ggc,aftB_S238G,1,a;t,g;c
213,AMI,3) Uncertain significance,NaN,aftB,aftB_W63Y,4268649;4268648,tgg,tat,aftB_W63Y,2,g;g,a;t
253,AMI,3) Uncertain significance,NaN,ccsA,ccsA_I123A,620257;620258,atc,gcc,ccsA_I123A,1,a;t,g;c
264,AMI,3) Uncertain significance,NaN,ccsA,ccsA_R131K,620281;620282;620283,cgt,aaa,ccsA_R131K,1,c;g;t,a;a;a
...,...,...,...,...,...,...,...,...,...,...,...,...
16028,STM,1) Assoc w R,NaN,rpsL,rpsL_K43R,781686;781687,aag,cgg,rpsL_K43R,1,a;a,c;g
16270,STM,3) Uncertain significance,NaN,gid,gid_E92G,4407928;4407927,gaa,ggc,gid_E92G,2,a;a,g;c
16426,STM,3) Uncertain significance,NaN,gid,gid_A138L,4407791;4407790,gcg,ttg,gid_A138L,1,g;c,t;t
17284,STM,3) Uncertain significance,NaN,gid,gid_G69I,4407998;4407997,ggt,att,gid_G69I,1,g;g,a;t
17463,STM,3) Uncertain significance,NaN,whiB7,whiB7_C20Y,3568621;3568620,tgc,tat,whiB7_C20Y,2,g;c,a;t

In [74]:
# Create masks for changes and for non-NaN values
change_mask = full_mapping['ref_nt'] != full_mapping['alt_nt']
non_nan_mask = ~full_mapping[['ref_nt', 'alt_nt']].isna().any(axis=1)

# Apply masks to filter the rows that need change
indices_to_change = full_mapping[change_mask & non_nan_mask].index

def get_from_to_nt(row):
    if isinstance(row['ref_nt'], str) and isinstance(row['alt_nt'], str):
        from_nt = ";".join([ref for ref, alt in zip(row['ref_nt'], row['alt_nt']) if ref != alt])
        to_nt = ";".join([alt for ref, alt in zip(row['ref_nt'], row['alt_nt']) if ref != alt])
        return from_nt, to_nt
    return "", ""

# Apply the function to relevant rows
results = full_mapping.loc[indices_to_change].apply(get_from_to_nt, axis=1)

# Assign results to the dataframe
full_mapping.loc[indices_to_change, 'from_nt'] = [res[0] for res in results]
full_mapping.loc[indices_to_change, 'to_nt'] = [res[1] for res in results]

In [75]:
full_mapping.query("first_diff_position.notna()")

,drug,confidence,variant_parsed,gene,variant,genome_index,ref_nt,alt_nt,variant_mapping,first_diff_position,from_nt,to_nt
193,AMI,3) Uncertain significance,NaN,aftB,aftB_S159A,4268362;4268360,tca,gcg,aftB_S159A,1,t;a,g;g
194,AMI,3) Uncertain significance,NaN,aftB,aftB_S238G,4268125;4268123,agt,ggc,aftB_S238G,1,a;t,g;c
213,AMI,3) Uncertain significance,NaN,aftB,aftB_W63Y,4268649;4268648,tgg,tat,aftB_W63Y,2,g;g,a;t
253,AMI,3) Uncertain significance,NaN,ccsA,ccsA_I123A,620257;620258,atc,gcc,ccsA_I123A,1,a;t,g;c
264,AMI,3) Uncertain significance,NaN,ccsA,ccsA_R131K,620281;620282;620283,cgt,aaa,ccsA_R131K,1,c;g;t,a;a;a
...,...,...,...,...,...,...,...,...,...,...,...,...
16028,STM,1) Assoc w R,NaN,rpsL,rpsL_K43R,781686;781687,aag,cgg,rpsL_K43R,1,a;a,c;g
16270,STM,3) Uncertain significance,NaN,gid,gid_E92G,4407928;4407927,gaa,ggc,gid_E92G,2,a;a,g;c
16426,STM,3) Uncertain significance,NaN,gid,gid_A138L,4407791;4407790,gcg,ttg,gid_A138L,1,g;c,t;t
17284,STM,3) Uncertain significance,NaN,gid,gid_G69I,4407998;4407997,ggt,att,gid_G69I,1,g;g,a;t
17463,STM,3) Uncertain significance,NaN,whiB7,whiB7_C20Y,3568621;3568620,tgc,tat,whiB7_C20Y,2,g;c,a;t

In [77]:
import pandas as pd

# Sample data
data = {
    'confidence': ['Uncertain significance']*5,
    'variant_parsed': [None]*5,
    'gene': ['aftB_S159A', 'aftB_S238G', 'aftB_W63Y', 'ccsA_I123A', 'ccsA_R131K'],
    'genome_index': ['4268362;4268360', '4268125;4268123', '4268649;4268648', '620257;620258', '620281;620282;620283'],
    'ref_nt': ['tca', 'agt', 'tgg', 'atc', 'cgt'],
    'alt_nt': ['gcg', 'ggc', 'tat', 'gcc', 'aaa'],
    'variant_mapping': ['aftB_S159A', 'aftB_S238G', 'aftB_W63Y', 'ccsA_I123A', 'ccsA_R131K'],
    'first_diff_position': ['1', '1', '2', '1', '1'],
    'from_nt': ['t;a', 'a;t', 'g;g', 'a;t', 'c;g;t'],
    'to_nt': ['g;g', 'g;c', 'a;t', 'g;c', 'a;a;a']
}

df = pd.DataFrame(data)

# Splitting multiple-valued columns by semicolon and exploding them into separate rows
columns_to_explode = ['genome_index', 'from_nt', 'to_nt']

for col in columns_to_explode:
    df[col] = df[col].str.split(';')

# Exploding each column sequentially
for col in columns_to_explode:
    df = df.explode(col)

df

,confidence,variant_parsed,gene,genome_index,ref_nt,alt_nt,variant_mapping,first_diff_position,from_nt,to_nt
0,Uncertain significance,None,aftB_S159A,4268362,tca,gcg,aftB_S159A,1,t,g
0,Uncertain significance,None,aftB_S159A,4268362,tca,gcg,aftB_S159A,1,t,g
0,Uncertain significance,None,aftB_S159A,4268362,tca,gcg,aftB_S159A,1,a,g
0,Uncertain significance,None,aftB_S159A,4268362,tca,gcg,aftB_S159A,1,a,g
0,Uncertain significance,None,aftB_S159A,4268360,tca,gcg,aftB_S159A,1,t,g
0,Uncertain significance,None,aftB_S159A,4268360,tca,gcg,aftB_S159A,1,t,g
0,Uncertain significance,None,aftB_S159A,4268360,tca,gcg,aftB_S159A,1,a,g
0,Uncertain significance,None,aftB_S159A,4268360,tca,gcg,aftB_S159A,1,a,g
1,Uncertain significance,None,aftB_S238G,4268125,agt,ggc,aftB_S238G,1,a,g
1,Uncertain significance,None,aftB_S238G,4268125,agt,ggc,aftB_S238G,1,a,c
1,Uncertain significance,None,aftB_S238G,4268125,agt,ggc,aftB_S238G,1,t,g
1,Uncertain significance,None,aftB_S238G,4268125,agt,ggc,aftB_S238G,1,t,c
1,Uncertain significance,None,aftB_S238G,4268123,agt,ggc,aftB_S238G,1,a,g
1,Uncertain significance,None,aftB_S238G,4268123,agt,ggc,aftB_S238G,1,a,c
1,Uncertain significance,None,aftB_S238G,4268123,agt,ggc,aftB_S238G,1,t,g
1,Uncertain significance,None,aftB_S238G,4268123,agt,ggc,aftB_S238G,1,t,c
2,Uncertain significance,None,aftB_W63Y,4268649,tgg,tat,aftB_W63Y,2,g,a
2,Uncertain significance,None,aftB_W63Y,4268649,tgg,tat,aftB_W63Y,2,g,t
2,Uncertain significance,None,aftB_W63Y,4268649,tgg,tat,aftB_W63Y,2,g,a
2,Uncertain significance,None,aftB_W63Y,4268649,tgg,tat,aftB_W63Y,2,g,t
2,Uncertain significance,None,aftB_W63Y,4268648,tgg,tat,aftB_W63Y,2,g,a
2,Uncertain significance,None,aftB_W63Y,4268648,tgg,tat,aftB_W63Y,2,g,t
2,Uncertain significance,None,aftB_W63Y,4268648,tgg,tat,aftB_W63Y,2,g,a
2,Uncertain significance,None,aftB_W63Y,4268648,tgg,tat,aftB_W63Y,2,g,t
3,Uncertain significance,None,ccsA_I123A,620257,atc,gcc,ccsA_I123A,1,a,g
3,Uncertain significance,None,ccsA_I123A,620257,atc,gcc,ccsA_I123A,1,a,c
3,Uncertain significance,None,ccsA_I123A,620257,atc,gcc,ccsA_I123A,1,t,g
3,Uncertain significance,None,ccsA_I123A,620257,atc,gcc,ccsA_I123A,1,t,c
3,Uncertain significance,None,ccsA_I123A,620258,atc,gcc,ccsA_I123A,1,a,g
3,Uncertain significance,None,ccsA_I123A,620258,atc,gcc,ccsA_I123A,1,a,c
3,Uncertain significance,None,ccsA_I123A,620258,atc,gcc,ccsA_I123A,1,t,g
3,Uncertain significance,None,ccsA_I123A,620258,atc,gcc,ccsA_I123A,1,t,c
4,Uncertain significance,None,ccsA_R131K,620281,cgt,aaa,ccsA_R131K,1,c,a
4,Uncertain significance,None,ccsA_R131K,620281,cgt,aaa,ccsA_R131K,1,c,a
4,Uncertain significance,None,ccsA_R131K,620281,cgt,aaa,ccsA_R131K,1,c,a
4,Uncertain significance,None,ccsA_R131K,620281,cgt,aaa,ccsA_R131K,1,g,a
4,Uncertain significance,None,ccsA_R131K,620281,cgt,aaa,ccsA_R131K,1,g,a
4,Uncertain significance,None,ccsA_R131K,620281,cgt,aaa,ccsA_R131K,1,g,a
4,Uncertain significance,None,ccsA_R131K,620281,cgt,aaa,ccsA_R131K,1,t,a
4,Uncertain significance,None,ccsA_R131K,620281,cgt,aaa,ccsA_R131K,1,t,a
4,Uncertain significance,None,ccsA_R131K,620281,cgt,aaa,ccsA_R131K,1,t,a
4,Uncertain significance,None,ccsA_R131K,620282,cgt,aaa,ccsA_R131K,1,c,a
4,Uncertain significance,None,ccsA_R131K,620282,cgt,aaa,ccsA_R131K,1,c,a
4,Uncertain significance,None,ccsA_R131K,620282,cgt,aaa,ccsA_R131K,1,c,a
4,Uncertain significance,None,ccsA_R131K,620282,cgt,aaa,ccsA_R131K,1,g,a
4,Uncertain significance,None,ccsA_R131K,620282,cgt,aaa,ccsA_R131K,1,g,a
4,Uncertain significance,None,ccsA_R131K,620282,cgt,aaa,ccsA_R131K,1,g,a
4,Uncertain significance,None,ccsA_R131K,620282,cgt,aaa,ccsA_R131K,1,t,a
4,Uncertain significance,None,ccsA_R131K,620282,cgt,aaa,ccsA_R131K,1,t,a
4,Uncertain significance,None,ccsA_R131K,620282,cgt,aaa,ccsA_R131K,1,t,a
4,Uncertain significance,None,ccsA_R131K,620283,cgt,aaa,ccsA_R131K,1,c,a
4,Uncertain significance,None,ccsA_R131K,620283,cgt,aaa,ccsA_R131K,1,c,a
4,Uncertain significance,None,ccsA_R131K,620283,cgt,aaa,ccsA_R131K,1,c,a
4,Uncertain significance,None,ccsA_R131K,620283,cgt,aaa,ccsA_R131K,1,g,a
4,Uncertain significance,None,ccsA_R131K,620283,cgt,aaa,ccsA_R131K,1,g,a
4,Uncertain significance,None,ccsA_R131K,620283,cgt,aaa,ccsA_R131K,1,g,a
4,Uncertain significance,None,ccsA_R131K,620283,cgt,aaa,ccsA_R131K,1,t,a
4,Uncertain significance,None,ccsA_R131K,620283,cgt,aaa,ccsA_R131K,1,t,a
4,Uncertain significance,None,ccsA_R131K,620283,cgt,aaa,ccsA_R131K,1,t,a